# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Agent
version:      0.03
version_from: lib/WWW/Agent.pm
installdirs:  site
requires:
    Algorithm::Diff:               1.11
    HTML::TreeBuilder:             3.13
    HTTP::Request:                 1.4
    HTTP::Response:                1.52
    Log::Log4perl:                 0.51
    LWP::UserAgent:                2.033
    Parse::RecDescent:             1.94
    POE:                           0.29
    Test::More:                    0.47
    URI:                           1.3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
